### ISSUE TITLE
Usage example in .README doesn't work.

### ISSUE THREAD

**Issue by Kubasinska** [bingsome/Roots#2]
```python
#import roots modules
from roots.core import Roots,Roots_math
from roots.kmd import KMDD
from roots.graphmethods import GraphMethods

#import a few helper libraries
import numpy as np
import random
import os

#generate some random parameters for roots to use
def return_random_params():
	a = random.choice(np.arange(1,3.0,0.25))
	b = random.choice(np.arange(300,475,25))
	c = random.choice(np.arange(1.5,3.0,0.25))
	d = random.choice(np.arange(300,425,25))
	return(a,b,c,d)

#create source point, target points, and pass them to Roots.
#call .grow() method and specify output .swc file to write results to
def make_axon(outputdir):
	a,b,c,d = return_random_params()
	source_point,targets = np.random.rand(300,3)*100.0
	root = Roots(source_point, targets, np.pi/a, b, np.pi/c, d, 100, KMDDproperties=dict(zip(['cluster_reduce','tri_edge_length_max','source','open_points'],[0.25,300,source_inner,new_points[:source_index]+new_points[source_index+1:]])))
	graph_nodes = root.grow()
	swcname = outputdir+axe_type+'_'+str(a)+'_'+str(b)+'_'+str(c)+'_'+str(d)+'.swc'
	root.to_swc(swcname) #save axon to swc
	return(root)

#finally run the make_axon function with the output directory as the input.
if __name__ == "__main__":
	root = make_axon(os.getcwd()+'/')
```

Running this code will give:

```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "<input>", line 23, in make_axon
ValueError: too many values to unpack (expected 2)
```

**Comment by bingsome** [comment]
You've caught me in a lurch and Roots has broken as a result. I have a new swcToolkit class and the .to_swc method has been moved there. Give me 24hrs and I'll clean it up. A lot of it has to do with the introduction of the microstructures class and how segments need to be broken up in order to make them persistent in morphology structures.

Happy to have someone making pull requests!

**Comment by bingsome** [comment]
Fixed. See new README. to_swc method has been moved to swcToolkit.
